### ISSUE TITLE
Missing font file Dosis Extended 700

### ISSUE THREAD

**Issue by AF-HAF-KARTOGRAF** [ruevko/Weekly-OSM#1]
In WeeklyOSM missing font Dosis Extended 700. Has this file extended Latin? https://weeklyosm.eu/cz/wp-content/themes/ephemeris-child/fonts/dosis/static/dosis-latin-ext-700.woff2

**Comment by AF-HAF-KARTOGRAF** [comment]
Now it is repaired. Thanks very much!

**Comment by call-me-matt** [comment]
Thank you for having reported this!

Unfortunately this repo is not related to the weeklyosm.eu website, even though it has the same name. If you want to reach out to the website team, it is best to write us an email or a comment on the website itself.

**Comment by ruevko** [comment]
@call-me-matt I wasn't aware of weeklyosm.eu existance when launching this repo.
I am willing to change this project's name to avoid this kind of situations.

**Comment by call-me-matt** [comment]
Hi. That is very kind of you, but I think it is alright - no need to change the name for us. We are aware of it now and you can redirect to us in case there is a new issue which does not relate to your stats. If you want to prevent confusion, you can of course add a remark in your readme. We would be happy about it :)
